apiVersion: v1
kind: Service
metadata:
  name: "tracking-system-svc"
  labels:
    app: "tracking-system"
spec:
  type: NodePort
  ports:
    - port: 30000
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app: "tracking-system"
