# Generated by Django 5.1.4 on 2025-01-12 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
