apiVersion: v1
kind: Service
metadata:
  name: db-master
spec:
  selector:
    app: db-master
  ports:
    - protocol: TCP
      port: {{ .Values.database.master.service.port }}
      targetPort: {{ .Values.database.master.service.port }}
  type: ClusterIP
