apiVersion: v1
kind: Service
metadata:
  name: db-slave
spec:
  selector:
    app: db-slave
  ports:
    - protocol: TCP
      port: {{ .Values.database.slave.service.port }}
      targetPort: {{ .Values.database.slave.service.port }}
  type: ClusterIP
