apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  database_password: {{ .Values.django.env.DATABASE_PASSWORD | b64enc | quote }}
  database_user: {{ .Values.django.env.DATABASE_USER | b64enc | quote }}
