apiVersion: v1
kind: Service
metadata:
  name: {{ include "phase-2.fullname" . }}-django
  labels:
    app: {{ include "phase-2.name" . }}
    component: django
spec:
  type: {{ .Values.django.service.type }}
  ports:
    - port: {{ .Values.django.service.port }}
      targetPort: {{ .Values.django.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "phase-2.name" . }}
    component: django
